version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'qc_automation_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: